modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="cyfone"
version="1.0.0"
displayName="ConfigYourWorld"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="conno, MCreator"

[[dependencies.cyfone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




